services:
  hexbot:
    build: .
    restart: unless-stopped
    ports:
      - '49152-49171:49152-49171'
    volumes:
      - ./config:/app/config
      - ./plugins:/app/plugins
      - ./data:/app/data
